USE [master]
ALTER DATABASE [Northwind] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [Northwind] FROM  DISK = N'D:\Microsoft SQL Server 2017\MSSQL14.MSSQLSERVER\MSSQL\Backup\Northwind.bak',  DISK = N'D:\Microsoft SQL Server 2017\MSSQL14.MSSQLSERVER\MSSQL\Backup\northwind_clean.bak' WITH  FILE = 1,  NOUNLOAD,  STATS = 5
ALTER DATABASE [Northwind] SET MULTI_USER


